# Uncomment this line to define a global platform for your project
platform :ios, '12.0' # Vagy a minimum iOS verzió, amit támogatsz

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Pods for your Flutter project
  # Ez az útvonal a projekt gyökérkönyvtárához képest van
  flutter_application_path = '../..'
  # A podhelper.rb fájl a 'ios/Flutter/' mappában található
  load File.join(flutter_application_path, 'ios', 'Flutter', 'podhelper.rb')

  flutter_install_all_ios_pods(flutter_application_path)

  target 'RunnerTests' do
    inherit! :complete
    # Pods for testing
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
